### ISSUE TITLE
Tracking issue for refactoring

### ISSUE THREAD

**Issue by atticus-sullivan** [atticus-sullivan/cluttealtex#29]
- [ ] rename `options` to `option_t` for the `require"option_type"`
- [ ] make naming of types only teal file (and variable name of the import) uniform (`_t`)
- [ ] `tex_engine` shouldn't be imported as `engine_t` (confusion with type-only teal files)
